# Site settings
title:          Solbin.tech
description:    "A typography-focused theme"
url:            "https://han-solbin.github.io/"

future: true

# Google Analytics
google_analytics:

# Author
author:
  name:         Han Solbin
  url:          https://github.com/Han-solbin
  email:

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Limit the number of posts generated in the feed
feedlimit:      10

paginate: 5

# Tuning
relatedpostsenabled: true # whether you want related posts enabled
tagrelationlevel: 2 # higher number corresponds to narrower targetting
maxrelatedposts: 3

wpm: 180 # read speed in words per minute

# Social
facebook:
twitter:
podcasturl:
